//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutPredkovApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsResultInventory
    {
        public int ItemsResultInventory1 { get; set; }
        public Nullable<int> ResultId { get; set; }
        public Nullable<int> InventoryResultId { get; set; }
    
        public virtual InventoryResult InventoryResult { get; set; }
        public virtual Result Result { get; set; }
    }
}
