//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutPredkovApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.CommonUse = new HashSet<CommonUse>();
            this.Inventory = new HashSet<Inventory>();
            this.Movement = new HashSet<Movement>();
            this.PersonalUse = new HashSet<PersonalUse>();
            this.WriteOffs1 = new HashSet<WriteOffs>();
        }
    
        public int InventoryNumber { get; set; }
        public string Name { get; set; }
        public int CategoryCode { get; set; }
        public double Cost { get; set; }
        public Nullable<System.DateTime> DatePurchase { get; set; }
        public string Manufacturer { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<int> WriteOffsId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommonUse> CommonUse { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual WriteOffs WriteOffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movement> Movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalUse> PersonalUse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WriteOffs> WriteOffs1 { get; set; }
    }
}
