//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PutPredkovApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomEntities : DbContext
    {
        public DiplomEntities()
            : base("name=DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CommonUse> CommonUse { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<InventoryResult> InventoryResult { get; set; }
        public virtual DbSet<ItemsResultInventory> ItemsResultInventory { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Movement> Movement { get; set; }
        public virtual DbSet<PersonalUse> PersonalUse { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WriteOffs> WriteOffs { get; set; }
    }
}
